name: Build and Release

on:
  push:
    branches: [ "main", 'dev' ]

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build package
              run: make pack

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                files: "*.zip"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}