name: Build and Release

on:
  push:
    branches: [ "main", 'dev' ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
    

env:
  NAME: reboottouefi
  DOMAIN: ubaygd.com
  FILE_EXT: zip 


jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install gettext
              run: sudo apt-get install gettext

            - name: Build package
              run: make pack

            - name: Upload Release Asset
              uses: actions/upload-artifact@v3
              with:
                name: release-asset
                path: $(NAME)@$(DOMAIN)-*.${FILE_EXT}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


            # - name: Create Release
            #   uses: softprops/action-gh-release@v2
            #   with:
            #     files: "*.zip"
            #   env:
            #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}